# Host to use for canonical URL generation (without trailing slash)
host: https://docs.example.com

# Header-related options
show_govuk_logo: true
service_name: My First Service
service_link: /
phase: Beta

# Links to show on right-hand-side of header
header_links:
  Documentation: /
  Expired page: /expired-page.html
  Expired with owner: /expired-page-with-owner.html
  Not expired page: /not-expired-page.html
  Single page nav: /single-page-nav.html

footer_links:
  Accessibility: /hidden-page.html
  Hidden Page: /hidden-page.html

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

google_site_verification: dstbao8TVS^DRVDS&rv76

enable_search: true

show_contribution_banner: true

github_repo: alphagov/example-repo
github_branch: source

redirects:
  /something/old.html: /index.html

api_path: source/pets.yml

# Optional global settings for the page review process
owner_slack_workspace: gds
default_owner_slack: '#2nd-line'
